from .tensorrt_convert import DYNAMIC_TRT_MODEL_CONVERSION
from .tensorrt_convert import STATIC_TRT_MODEL_CONVERSION
from .tensorrt_loader import TensorRTLoader

NODE_CLASS_MAPPINGS = {
        "DYNAMIC_TRT_MODEL_CONVERSION": DYNAMIC_TRT_MODEL_CONVERSION,
        "STATIC_TRT_MODEL_CONVERSION": STATIC_TRT_MODEL_CONVERSION,
        "TensorRTLoader": TensorRTLoader
}


NODE_DISPLAY_NAME_MAPPINGS = {
    "DYNAMIC_TRT_MODEL_CONVERSION": "DYNAMIC TRT_MODEL CONVERSION",
    "STATIC_TRT_MODEL_CONVERSION": "STATIC TRT MODEL CONVERSION",
    "TensorRTLoader": "TensorRT Loader"
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']