from .tensorrt_convert import DYNAMIC_TRT_MODEL_CONVERSION
from .tensorrt_convert import STATIC_TRT_MODEL_CONVERSION
from .tensorrt_loader import TensorRTLoader
from .tensorrt_vae_loader import TensorRTVAELoader
from .tensorrt_convert_vae import DYNAMIC_TRT_VAE_DECODER_CONVERSION
from .tensorrt_convert_vae import DYNAMIC_TRT_VAE_ENCODER_CONVERSION
from .tensorrt_convert_vae import STATIC_TRT_VAE_DECODER_CONVERSION
from .tensorrt_convert_vae import STATIC_TRT_VAE_ENCODER_CONVERSION

NODE_CLASS_MAPPINGS = {
        "DYNAMIC_TRT_MODEL_CONVERSION": DYNAMIC_TRT_MODEL_CONVERSION,
        "STATIC_TRT_MODEL_CONVERSION": STATIC_TRT_MODEL_CONVERSION,
        "TensorRTLoader": TensorRTLoader,
        "TensorRTVAELoader": TensorRTVAELoader,
        "DYNAMIC_TRT_VAE_DECODER_CONVERSION": DYNAMIC_TRT_VAE_DECODER_CONVERSION,
        "DYNAMIC_TRT_VAE_ENCODER_CONVERSION": DYNAMIC_TRT_VAE_ENCODER_CONVERSION,
        "STATIC_TRT_VAE_DECODER_CONVERSION": STATIC_TRT_VAE_DECODER_CONVERSION,
        "STATIC_TRT_VAE_ENCODER_CONVERSION": STATIC_TRT_VAE_ENCODER_CONVERSION
}


NODE_DISPLAY_NAME_MAPPINGS = {
    "DYNAMIC_TRT_MODEL_CONVERSION": "DYNAMIC TRT_MODEL CONVERSION",
    "STATIC_TRT_MODEL_CONVERSION": "STATIC TRT MODEL CONVERSION",
    "TensorRTLoader": "TensorRT Loader",
    "TensorRTVAELoader": "TensorRT VAE Loader",
    "DYNAMIC_TRT_VAE_DECODER_CONVERSION": "DYNAMIC TRT VAE DECODER CONVERSION",
    "DYNAMIC_TRT_VAE_ENCODER_CONVERSION": "DYNAMIC TRT VAE ENCODER CONVERSION",
    "STATIC_TRT_VAE_DECODER_CONVERSION": "STATIC TRT VAE DECODER CONVERSION",
    "STATIC_TRT_VAE_ENCODER_CONVERSION": "STATIC TRT VAE ENCODER CONVERSION"
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']